### ISSUE TITLE
Play at the same time as other audio (Ignore Audio Focus)

### ISSUE THREAD

**Issue by boffyb** [ashutoshgngwr/noice#578] opened 2021-04-01 09:48 UTC
### Is your feature request related to a problem? Please describe.
A lot of Bluetooth headphones mute the audio when it dips below a certain level. I don't know if this is a crude form of noise suppression or a way to save power.

They generally don't have a way to turn this feature off. 

When listening to an audiobook, podcast, or other spoken word content, this can clip off the beginnings and ends of words.

### Describe the solution you'd like
Your app can generate constant sounds like pink noise at whatever level I like.

If this noise could keep playing while I'm listening to my audiobook, it would force my headphones to stay active and not clip off quiet bits of words.

I think this setting is called "Ignore Audio Focus" in other apps

**Comment by ashutoshgngwr** [comment] 2021-04-11 06:21
It is partially implemented. Start your audiobook app first and then Noice. Noice requests that other apps duck their volume when it plays, so other apps, in general, should lower their volume, but continue to play. Let me know if it resolves your issue.

Also, ignoring audio focus entirely breaks the best practices suggested by the Android Framework. I am personally against it. Perhaps something else could be done?

**Comment by ashutoshgngwr** [comment] 2021-04-23 11:12
Duplicate of #462

**Closed by ashutoshgngwr** 2021-04-23 11:12 UTC
Labels: enhancement
