### ISSUE TITLE
Can you add Pomodoro Timer Feature…?

### ISSUE THREAD

**Issue by Nimendra11** [ashutoshgngwr/noice#912] opened 2022-01-25 02:07 UTC
## Can you add pomodoro timer like this 👇👇

 1.end of pomodoro session noice app says,  
            hii buddy, pomodoro session is over. Take a little break.(pausing playing noises)
 2.and end of break noice app says,
            buddy, our break is over, let's go back to work. (starting playing noises)

**Comment by ashutoshgngwr** [comment] 2022-01-25 03:35
I will look into it post v2 release. Right now, all efforts are directed at finishing the v2 implementation.

**Comment by ashutoshgngwr** [comment] 2022-01-25 06:13
just noticed that it is duplicate of #443

**Closed by ashutoshgngwr** 2022-01-25 06:13 UTC
Labels: enhancement, always-fresh
