### ISSUE TITLE
Custom sounds

### ISSUE THREAD

**Issue by reykwan** [ashutoshgngwr/noice#142] opened 2020-04-23 21:31 UTC
Please add a feature for users to add their own sounds

**Comment by ashutoshgngwr** [comment] 2020-04-24 04:50
@reykwan This is something I have deliberately avoided adding to the app. If I remember correctly, this was proposed in on of the earlier issues as well. In what scenarios, would you want custom sounds? Please note that the goal of the project is to be a noise generator.

**Comment by yashpalgoyal1304** [comment] 2020-05-18 16:02
I would want to use custom sounds when i want to use:
- the noise of my choice
- low key music from youtube
- soundtracks of movies
- binaural beats (or other similar tones)

----

Anyways, thanks for the awesome app. This is exactly what i was looking for (after this suggestion is accepted tbh, but this is awesome already as well).

**Comment by ashutoshgngwr** [comment] 2020-05-18 17:48
@yashpalgoyal1304 I myself listen to music sometimes while generating a little ambience on the side. Noice supports playback alongside other apps. This implies that you can still go ahead and do any of the things you mentioned with any of the other apps and continue to use Noice for generating ambience.

When you play an audio from any other app while Noice is playing, Noice will pause at first. But if you resume it after the other app has started playing, Noice will resume without stopping the other app. This is by design because we need to respect audio playback from other apps.

Hope this helps.

**Comment by yashpalgoyal1304** [comment] 2020-05-18 18:11
thanks for the reply. 

I get it that the last 3 things can be done in other apps too, but i cant use other apps for HQ noise of my choice. I tried doing it via VLC, MX Player, KODI, and sometimes MiXplorer player too playing all at the same time, and it turned into a mess pretty quickly.

**Comment by ashutoshgngwr** [comment] 2020-05-18 18:20
@yashpalgoyal1304 I understand the sentiment but my concern with this feature has always been the separation of concerns. If Noice allows users to import custom sounds, its not a noise generator anymore. Perhaps what is being proposed here is better suited for an audio mixing app or an app which does multi track playback in general.

**Comment by yashpalgoyal1304** [comment] 2020-05-18 18:25
Yeah, i agree. And i tried searching for those too (sorry if it feels patronizing or what! i am not rude). And couldnt find an app for multi-track playback. The audio mixing or DeeJay apps were overkill (resource consumption) and under deliver (only 2 tracks) for my requirements.

**Comment by ashutoshgngwr** [comment] 2020-05-18 18:37
@yashpalgoyal1304 I am sorry but I can't help you there. Thanks for understanding.

**Comment by ashutoshgngwr** [comment] 2020-05-19 12:43
I am closing this issue because this feature won't be implemented. I'll also pin this issue to further reference.

**Closed by ashutoshgngwr** 2020-05-19 12:43 UTC
Labels: enhancement
